repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
        args: [ '--unsafe' ]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

    # ruff
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.255
    hooks:
    -   id: ruff

    # mypy
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-PyYAML == 6.0]
